export const dominData = [
  {
    serialno: 'SN0000f43',
    type: 'S4 Pro',
    location: 'Site 1 Cheddar UK',
    status: 'Active',
    imageSRC: '../../assets/image/s4-pro.png',
  },
  {
    serialno: 'SN0000g96',
    type: 'S6 Pro',
    location: 'Site 1 Cheddar UK',
    status: 'Error',
    imageSRC: '../../assets/image/s4-pro.png',
  },
  {
    serialno: 'SN0000h56',
    type: 'Fast',
    location: 'vehicle, Cheddar UK',
    status: 'Active',
    imageSRC: '../../assets/image/s4-pro.png',
  },
  {
    serialno: 'SN0000h56',
    type: 'Fast',
    location: 'vehicle, Cheddar UK',
    status: 'Active',
    imageSRC: '../../assets/image/s4-pro.png',
  },
  {
    serialno: 'SN0000h56',
    type: 'Fast',
    location: 'vehicle, Cheddar UK',
    status: 'Active',
    imageSRC: '../../assets/image/s4-pro.png',
  },
  {
    serialno: 'SN0000h56',
    type: 'Fast',
    location: 'vehicle, Cheddar UK',
    status: 'Active',
    imageSRC: '../../assets/image/s4-pro.png',
  },
  {
    serialno: 'SN0000h56',
    type: 'Fast',
    location: 'vehicle, Cheddar UK',
    status: 'Active',
    imageSRC: '../../assets/image/s4-pro.png',
  },
  {
    serialno: 'SN0000h56',
    type: 'Fast',
    location: 'vehicle, Cheddar UK',
    status: 'Active',
    imageSRC: '../../assets/image/s4-pro.png',
  },
  {
    serialno: 'SN0000h56',
    type: 'Fast',
    location: 'vehicle, Cheddar UK',
    status: 'Active',
    imageSRC: '../../assets/image/s4-pro.png',
  },
  {
    serialno: 'SN0000h56',
    type: 'Fast',
    location: 'vehicle, Cheddar UK',
    status: 'Active',
    imageSRC: '../../assets/image/s4-pro.png',
  },
];
